### ISSUE TITLE
I'm not getting any results in Firefox ...

### ISSUE THREAD

**Issue by dhannotte** [rufuspollock-okfn/wikipediajs#8]
... and IE says "'WIKIPEDIA' is not defined." 

Please tell me what I'm doing wrong? You can take a look at my HTML source code here: 

http://www.rosenfels.org/Test1.htm

Thanks very much!

**Comment by rufuspollock** [comment]
@dhannotte ok an immediate thing would be to load the library from http://okfnlabs.org/wikipediajs/wikipedia.js rather than https://raw.github.com/okfn/wikipediajs/master/wikipedia.js as the latter is now working (at least for me in chrome).

(NB: I know the instructions said to use that link - I've just fixed the instructions to new url i've just given you!)

**Comment by dhannotte** [comment]
Dear Dr. Pollock,

```
 Thanks so much for getting back to me! I believe we're making 
```

progress. However this time Internet Explorer says '$ is undefined' and 
Firefox still shows no results but puts the following error message in 
their browser console:

ReferenceError: $ is not defined                          wikipedia.js:70.

```
 You can see my source code at http://www.rosenfels.org/Test1.htm, 
```

and I have attached .PNG's of the two error messages.

Dean

P.S. My email address is _dean@hannotte.com_. If it doesn't work, go to 
Dean's Den (www.hannotte.com) or the Paul Rosenfels Community 
(www.rosenfels.org) and look for alternative contact instructions. If 
neither of these are helpful, google "Dean Hannotte" and hope that the 
world hasn't completely forgotten about me. If you're a friend I really 
should have replied to by now, contact Rachel Bartlett at 
_rachel.bartlett@nyc.rr.com_ for further information. And, if you have 
my phone number, please remember that I work nights and don't answer the 

## phone until around 2:00 PM.

**Comment by rufuspollock** [comment]
have you included jquery in the page? you'll need to do that :-)

**Comment by dhannotte** [comment]
Okay! This time Firefox says:

15:35:38.010 TypeError: info is undefined Test1.htm:15
15:35:38.594 TypeError: callback is not a function wikipedia.js:43

Dean

P.S. My email address is _dean@hannotte.com_. If it doesn't work, go to 
Dean's Den (www.hannotte.com) or the Paul Rosenfels Community 
(www.rosenfels.org) and look for alternative contact instructions. If 
neither of these are helpful, google "Dean Hannotte" and hope that the 
world hasn't completely forgotten about me. If you're a friend I really 
should have replied to by now, contact Rachel Bartlett at 
_rachel.bartlett@nyc.rr.com_ for further information. And, if you have 
my phone number, please remember that I work nights and don't answer the 

## phone until around 2:00 PM.

**Comment by dhannotte** [comment]
For some reason the new version with jquery doesn't work in Chrome 
either for me. I've attached the error message. You can see the source 
at http://www.rosenfels.org/Test1.htm

Dean

P.S. My email address is _dean@hannotte.com_. If it doesn't work, go to 
Dean's Den (www.hannotte.com) or the Paul Rosenfels Community 
(www.rosenfels.org) and look for alternative contact instructions. If 
neither of these are helpful, google "Dean Hannotte" and hope that the 
world hasn't completely forgotten about me. If you're a friend I really 
should have replied to by now, contact Rachel Bartlett at 
_rachel.bartlett@nyc.rr.com_ for further information. And, if you have 
my phone number, please remember that I work nights and don't answer the 

## phone until around 2:00 PM.

**Comment by dhannotte** [comment]
Dear Dr. Pollock,

```
 Have business pressures prevented you from helping me shake out the 
```

kinks in wikipediajs, or have you decided to abandon the project? I need 
to know because this is holding back a project involving more than just 
one developer. Thanks.

Dean

P.S. My email address is _dean@hannotte.com_. If it doesn't work, go to 
_my website_ <www.hannotte.com> or _the Paul Rosenfels Community 
website_ <www.rosenfels.org> and look for alternative contact 
instructions. If neither of these are helpful, google "Dean Hannotte" 
and hope that the world hasn't completely forgotten about me. If you're 
a friend I really should have replied to by now, contact _Rachel 
Bartlett_ mailto:rachel.bartlett@nyc.rr.com for further information. 
And, if you have my phone number, please remember that I work nights and 

## don't answer the phone until around 2:00 PM.
